### ISSUE TITLE
R-76 KC Magnum has no Revolver belt rig holster sprite.

### ISSUE THREAD

**Issue by Trelus** [tgstation/TerraGov-Marine-Corps#13774] opened 2023-08-12 18:40 UTC
### Description

When you place the R-76 KC Magnum Requisition revolver in the revolver belt holster rig, the rig has an error holstered rather then the Revolver. Seems the KC Magnum lacks a holster sprite.

### Test Merges

[#13515: 'Adds 2 new tadpole models updating: to make grief poles less griefy' by XANAv2 at commit e52d05bff0](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13515)
[#13308: 'New Xenomorph : Baneling' by Zar000 at commit df11d10991](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13308)
[#13546: 'Port tg statpanel' by forestbbbbbbb at commit 9cb28c470c](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13546)
[#13758: 'Fixes jobs not scaling if nobody readies up + fix a thing I broke' by ivanmixo at commit dd52aad4b3](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13758)
[#13626: 'Slumbridge' by chizzy376 at commit 9f767414f7](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13626)

### Reproduction Steps

1. Obtain a R-76 KC Magnum revolver.
2. Remove the stock from the revolver.
3. Get a Revolver belt rig.
4. Place the revolver inside the belt holster.
5. Observe the holster.

**Comment by chizzy376** [comment] 2023-08-13 19:53
duplicate of #13057

**Closed** 2024-03-31 03:09 UTC
Labels: Bug
