### ISSUE TITLE
storage module bug

### ISSUE THREAD

**Issue by isotope436** [tgstation/TerraGov-Marine-Corps#10270] opened 2022-05-22 01:44 UTC
### Description

any weapon that you put in the general purpose storage module for jeager doesnt save attachments went taken out of the loadout vendor. at current iv only seen this occur with the mp19 but thats the only gun i use with it so that may be why.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [14704](https://scrubby.melonmesa.com/round/14704)
BYOND Version: 514.1583
Server revision compiled on: 
Master commit: [a502e969f7dbd9843f8d0cf6fbd489823c0832ac](https://github.com/tgstation/TerraGov-Marine-Corps//commit/a502e969f7dbd9843f8d0cf6fbd489823c0832ac)
The following pull requests are currently test merged:
[#10129: 'Med rework' by goose4429 at commit 7a61b19915](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10129)
[#10213: 'Fire armor pass' by DeltaFire15 at commit 3f7e318793](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10213)

Local commit: 4353e7f7a9058fc5e93efaca05b5fc2b8004d9a8
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

put any weapon (that will fit) with attachments into the general purpose storage module (the mp19 i know has this issue)
save the loadout and then take it back out your gun shouldnt have any attachments on it

**Comment by Xander3359** [comment] 2023-02-28 21:49
Duplicate of https://github.com/tgstation/TerraGov-Marine-Corps/issues/9349

**Closed** 2023-02-28 21:53 UTC
Labels: Bug
