### ISSUE TITLE
Flak 88 spawns 2 Flaks, only one is real.

### ISSUE THREAD

**Issue by Teragenic** [tgstation/TerraGov-Marine-Corps#15169] opened 2024-02-23 01:59 UTC
### Description

Flak 88 when vended spawns 2 flak 88s. One in hand and one on the vendor. 

### Test Merges

N/A 

### Reproduction Steps

Vend flak 88

### Screenshots

![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/67575979/371f2326-5715-4b5e-b06a-ac864ff06e0b)

**Comment by lbnesquik** [comment] 2024-02-23 17:03
Ghost Division

**Comment by coldironwarrior** [comment] 2024-02-25 06:46
Duplicate of #14095
Related to #14133

**Closed** 2024-03-15 19:17 UTC
Labels: Bug
