### ISSUE TITLE
When dragged to uppering floor in req, crate falls down (still can be dragged after falling) and appears here

### ISSUE THREAD

**Issue by Monikawales** [tgstation/TerraGov-Marine-Corps#947] opened 2019-03-03 02:21 UTC
## Reproduction:
![image](https://user-images.githubusercontent.com/45321263/53690049-2fdca200-3d74-11e9-9ce0-2f8aebca37b0.png)

**Comment by Monikawales** [comment] 2019-03-03 02:22
Drag a crate here
![image](https://user-images.githubusercontent.com/45321263/53690054-42ef7200-3d74-11e9-9a47-856d4ea8db09.png)
When platform is raising

**Comment by Alterist** [comment] 2019-03-03 14:08
Sorta Intended behaviour, anything that falls down the req elevator gets dumped by the chute in the storage room, the real issue is the rails dropping before the elevator is completely up

**Comment by MrStonedOne** [comment] 2019-03-04 19:31
Please do not leave format template noise in your issue body. Remove any section that does not apply.

**Comment by DominikPanic** [comment] 2019-03-06 23:46
@Alterist Fix/wontfix?

**Comment by Rohesie** [comment] 2019-03-11 03:32
This will end up changing with the shuttle rework, as the req platform is an abstract shuttle.
The issue is what Alterist pointed, in any case. The railings should drop only after the shuttle arrives.
@spookydonut , think you can add that behavior?

**Closed** 2019-05-04 18:08 UTC
Labels: Bug
