### ISSUE TITLE
Throwing items doesn't cancel or change momentum in space

### ISSUE THREAD

**Issue by Mechswordsman** [tgstation/TerraGov-Marine-Corps#11825] opened 2022-12-30 04:05 UTC
### Description

If you throw a item, it doesn't cause you to stop moving, or move in the opposite direction in space.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [18654](https://scrubby.melonmesa.com/round/18654)
BYOND Version: 514.1589
Server revision compiled on: 
Master commit: [0b9f0089c04a194e0db82e04dfc055d1766d6742](https://github.com/tgstation/TerraGov-Marine-Corps//commit/0b9f0089c04a194e0db82e04dfc055d1766d6742)
The following pull requests are currently test merged:
[#10418: 'Changes Shrike's abilties, buffs speed.' by Losenis at commit 93f000c4ad](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10418)
[#11721: 'Xeno buff of the year (Pre-shutter mazing ability)' by MLGTASTICa at commit 48e45a4fe7](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11721)
[#11765: 'King rework - revived' by Lumipharon at commit bf412ff294](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11765)
[#11726: 'Ports Delta Station' by RipGrayson at commit e60301bd74](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11726)
[#11598: 'Adds the AGLS-37' by Pariah919 at commit be7117c451](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11598)

Local commit: 58f831064d7aa6e679da76969f095e25e3ad3722
Server tools version: 5.2.3

### Reproduction Steps

Get thrown by one thing in space

Try to throw object to cancel momentum so you don't get space

Watch as you continue to fly anyways and perma die.

**Comment by Xander3359** [comment] 2023-04-15 01:45
There is no momentum in space. You can simply move around with arrow keys. This is not a bug and I'd close it tbh.

**Closed** 2023-05-12 12:22 UTC
Labels: Bug
