### ISSUE TITLE
Synthesized Instruments are borked

### ISSUE THREAD

**Issue by Kapu1178** [tgstation/TerraGov-Marine-Corps#8186] opened 2021-09-06 02:14 UTC
### Description

Synthesized instruments appear to completely fucking break after the first line of notes. This is a TGMC-exclusive issue, Beestation and Baystation's instruments work just fine.

### Test Merges

BYOND Version: 514.1557
Server revision compiled on: 
Master commit: 015398a4e616735b792385641f602fc14ed46557
The following pull requests are currently test merged:
#7618: 'King of the hill Civil War' by BraveMole at commit 1f4adf7191
#8120: 'Adds marine motorbikes' by TiviPlus at commit c48d10d56a
#7815: 'Adds movement and direction switch for scopes with ctrl+Wasd' by SplinterGP at commit 49b21ffb9a

### Reproduction Steps

1. Get a Synthesizer
2. Change the instrument type to any synthesized one
3. Play a song
4. Listen

**Comment by BraveMole** [comment] 2021-09-07 11:18
Duplicate of another issue

**Closed** 2021-09-07 11:18 UTC
Labels: Bug
