### ISSUE TITLE
FOB can be invaded through shutters via acid hole crawling

### ISSUE THREAD

**Issue by terranaut1** [tgstation/TerraGov-Marine-Corps#3959] opened 2020-04-30 22:00 UTC
## Testmerges:

#3948 #3956 #3957 #3950 #3902 #3916 #3936 #3944 #3924 #3912 #3935 #3938 #3937 #3940 #3955 #3953 #3952 #3958

## Reproduction:

Inspect tile
Acid the wall
Crawl through and pop out on the other side

Seen on Big Red, probably possible on other maps too

**Comment by psykzz** [comment] 2020-04-30 22:40
Thanks for the post but this is a duplicate of https://github.com/tgstation/TerraGov-Marine-Corps/issues/3738

**Closed by psykzz** 2020-04-30 22:40 UTC

**Comment by terranaut1** [comment] 2020-04-30 22:44
oops
