### ISSUE TITLE
robot eye and visors

### ISSUE THREAD

**Issue by Starfirejordan** [tgstation/TerraGov-Marine-Corps#10087] opened 2022-04-28 19:53 UTC
### Description

robots eye use to change color with whatever eye piece they used
green for medical
blue for SG mount sight
it would just stay red with imagiers

but now it just having the visor sprite overly onto the robot instead of changing the eye color like it use to

### Test Merges

https://github.com/tgstation/TerraGov-Marine-Corps//pull/9772
https://github.com/tgstation/TerraGov-Marine-Corps//pull/9977
https://github.com/tgstation/TerraGov-Marine-Corps//pull/10008
https://github.com/tgstation/TerraGov-Marine-Corps//pull/9979

### Reproduction Steps

just wear any eye piece as robot and yell see it.

### Screenshots

![image](https://user-images.githubusercontent.com/102649696/165834207-e86eb6ab-8819-4b08-bfe5-c3472cde6e55.png)
![image](https://user-images.githubusercontent.com/102649696/165834286-170b0aa9-b857-4fa2-becd-047c19d5bf6c.png)
![image](https://user-images.githubusercontent.com/102649696/165834311-2bfcb9b9-a316-4fcd-a872-a9482dd78dfa.png)

**Comment by Lumipharon** [comment] 2022-05-01 21:21
Caused by #10033 
I'll need to check if the code in question can just be pasted back in.

**Comment by Lumipharon** [comment] 2022-05-09 00:38
Fixed by #10141

**Closed** 2022-08-03 21:48 UTC
Labels: Sprite issue
