### ISSUE TITLE
Hive Leader Pheromones Broke(?)

### ISSUE THREAD

**Issue by Shadow-Quill** [tgstation/TerraGov-Marine-Corps#1085] opened 2019-03-17 05:10 UTC
## Reproduction:

1) Mark xeno as hive leader as Queen.
2) Notice how pheromones are broken(?)
<hr>

Can't elaborate due to me not knowing how they're broke.

**Comment by DominikPanic** [comment] 2019-03-17 11:27
Duplicate of #1006

**Closed by DominikPanic** 2019-03-17 11:27 UTC
