### ISSUE TITLE
Light Scout helmet is invisible as an item, can't be taken off by wearer

### ISSUE THREAD

**Issue by Shirbu** [tgstation/TerraGov-Marine-Corps#5938] opened 2021-02-06 15:42 UTC
## Description:
The light scout jaeger helmet has no item sprite that is visible. Thus, it cannot normally be clicked. It can, however, be picked up using the right-click menu, and put on. 

This results in it being irremovable, except by another marine taking it off your person, as you cannot click on the helmet icon on your head, and you cannot right click menu it off either.

## Reproduction:
1. Buy the light scout jaeger set
2. Right click to find the invisible scout helmet
3. Put it on like a dumbass
4. Beg another marine to help you get it off
![image](https://user-images.githubusercontent.com/23252965/107122819-e560db80-684e-11eb-8dd0-bedc5f24a793.png)

**Comment by Shirbu** [comment] 2021-02-06 15:43
![image](https://user-images.githubusercontent.com/23252965/107122839-0f1a0280-684f-11eb-9968-6c49a77a3467.png)

**Comment by TGCMbetcher** [comment] 2021-02-07 01:42
Invisahelmet (TM) is a feature not a bug. Bait hunters to deep dive for the decap today.

**Comment by SkeletalElite** [comment] 2021-02-07 02:12
> Invisahelmet (TM) is a feature not a bug. Bait hunters to deep dive for the decap today.

You can see it on your character sprite just not on the floor or in your hand.

**Comment by TiviPlus** [comment] 2021-02-14 14:54
Should be fixed now

**Closed by TiviPlus** 2021-02-14 14:54 UTC
