### ISSUE TITLE
Old tank swap weapons + press OK bug

### ISSUE THREAD

**Issue by Monikawales** [tgstation/TerraGov-Marine-Corps#962] opened 2019-03-03 20:39 UTC
## Reproduction:
1. Open Swap weapons window
2. Press OK while window over game screen (OK button must be over world screen)
3. Cannon shoots exact point where you clicked OK by mouse cursor (SINGLE CLICK)

**Comment by DominikPanic** [comment] 2019-03-03 22:06
Duplicate of #483 since it's related to clicks being relayed

**Closed by DominikPanic** 2019-03-03 22:06 UTC
