### ISSUE TITLE
Binocular weirdness the second: Now 100% Cargo Tug free!

### ISSUE THREAD

**Issue by CoreFlare** [tgstation/TerraGov-Marine-Corps#2887] opened 2019-09-08 19:24 UTC
## Testmerges:

None.

## Explanation:

In this issue, I will be listing two bugs, both coming from the same thing. Binocular weirdness. Basically, you use the binoculars and then use them again to cancel the view. I used scout tactical binoculars for this, as they have CAS and partial NV.

The first one up is that using Z to exit binocular mode keeps binocular NV, and removes the NV if you zoom in a second time, allowing you to use scout NV.

The second one up is using laser targeting outside of binoculars, by exiting bino view with Z twice.

## Reproduction:

For the first bug, you will need any binoculars that have partial NV. I recommend the scout binos.

Step 1: Have binos in hand.

Step 2: Use binos with Z to zoom in.

Step 3: Use binos with Z to zoom out.

You should have the bino NV effect in normal view. If you press Z again, then you get whatever view you normally have in bino view, so for example scout NV sight.

For the second bug, follow these extra steps.

Step 4: Use binos with Z to zoom in.

Step 5: Use binos with Z to zoom out.

Step 6: Put binos away.

Now, when you Ctrl+Click something, instead of dragging it like normal, you'll start laser targeting it.

To cancel both bugs, simply follow these steps.

Step 1: Use binos with Z to zoom in.

Step 2: Move to zoom out.

## Effects:

For the first bug, it's self explanatory. However, it's effects are much more devastating. For one, if you have scout NV, then you can laze through walls, easily see far ahead terrain, scout out areas that have resin walls far ahead of normal view, etcetera. And, if you don't have scout sight, then you can get bino NV from doing this bug pretty easily.

For the second, it has some quirky effects. First, you can't use Ctrl+Click to drag stuff while it's active, you can only use Pull from the context menu in RClick. Second, it's like the first bug, where you can use this to laze through walls, although that would be drastically less useful for anything other than intimidation.

## Disclaimer:

I put two bugs in the same bug report because I believe they're caused by the same thing. If I need to make separate reports for things like this in future, please tell me.

**Comment by DominikPanic** [comment] 2019-09-08 19:40
Fixed in latest commit of #2814 though it's not caused by it

**Closed by DominikPanic** 2019-09-08 19:40 UTC
Labels: Bug
