### ISSUE TITLE
Xenos can't slash/melt certain objects.

### ISSUE THREAD

**Issue by Urthrem** [tgstation/TerraGov-Marine-Corps#3035] opened 2019-09-29 16:43 UTC
This is going to be for people to drop in their findings that they can't melt/slash as xenos.

So far I found out that reinforced and standard windoors cannot be slashed/melted and give 'Stares at it cluelessly' text upon trying to melt or attack it.

Another one are shooting targets. More to come

**Comment by Rohesie** [comment] 2019-10-01 00:26
This is a duplicate of #3030
Please open another issue if you find other things.

**Closed by Rohesie** 2019-10-01 00:26 UTC
