### ISSUE TITLE
No one has access to the black evac doors during evac.

### ISSUE THREAD

**Issue by Hughgent** [tgstation/TerraGov-Marine-Corps#1456] opened 2019-05-03 19:34 UTC
## Testmerges:

#1186, #1448, #1449, #1450, #1451, #1452, #1453, #1444, #1337, #1446, #1445, #1438, #1439, #1440, #1434, #1375

## Reproduction:

During the first round of today. Evacuation was called. several people attempted to enter the escape pods but the doors were not opening.

I am certain that the orange doors beyond the black doors were open, but no one could get to those.

**Comment by DominikPanic** [comment] 2019-05-03 19:37
Duplicate of #1387

**Closed by DominikPanic** 2019-05-03 19:37 UTC
