### ISSUE TITLE
ASRS teleporter becomes mountable

### ISSUE THREAD

**Issue by heffy117** [tgstation/TerraGov-Marine-Corps#10411] opened 2022-06-07 23:45 UTC
### Description

Holding a HSG-102 in one hand (not deployed) and a ASRS teleporter pad in the other and then deploying said teleporter causes the teleporter to become dense and give the message "You should be behind the ASRS Bluespace teleporter to man it!" Wrenching it and redeploying fixes it.

### Test Merges

Round ID: [14962](https://scrubby.melonmesa.com/round/14962)
BYOND Version: 514.1583
Server revision compiled on: 
Master commit: [e091f4da76880e9672a4ba4db27a26e6d2255d00](https://github.com/tgstation/TerraGov-Marine-Corps//commit/e091f4da76880e9672a4ba4db27a26e6d2255d00)
The following pull requests are currently test merged:
[#10316: 'Heart and lung damage affect stamina, health and speed' by BraveMole at commit 7e1d99b55d](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10316)

Local commit: 011dd00cd8c29a9ba4c4c57be7b556b3e1a04dd8
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

Get HSG-102, get ASRS teleporter (not the sell one), have both undeployed and in each hand, deploy the teleporter, click teleporter. Teleporter now acts like a solid object. Tossing/dropping the HSG-102 doesn't change the teleporter still being a "mountable" state.

**Comment by Lumipharon** [comment] 2022-06-08 01:17
Duplicate of #9970
@BraveMole pls

**Comment by heffy117** [comment] 2022-06-08 01:31
I got told to open a bug report so dont yell at me

**Comment by heffy117** [comment] 2022-06-08 01:32
I got told to open a bug report so

**Closed** 2022-06-11 21:29 UTC
Labels: Bug
