### ISSUE TITLE
Autodoc ejection runtime

### ISSUE THREAD

**Issue by TiviPlus** [tgstation/TerraGov-Marine-Corps#3896] opened 2020-04-20 16:24 UTC
## Testmerges:

master

## Reproduction:

[18:19:26] Runtime in autodoc.dm, line 677: Cannot execute null.incapacitated().
verb name: Eject Med-Pod (/obj/machinery/autodoc/verb/eject)
src: the autodoc medical system (/obj/machinery/autodoc)
src.loc: the floor (66,21,3) (/turf/open/floor/mainship)
call stack:
the autodoc medical system (/obj/machinery/autodoc): Eject Med-Pod()
the autodoc medical system (/obj/machinery/autodoc): Destroy(0)
qdel(the autodoc medical system (/obj/machinery/autodoc), 0)
the autodoc medical system (/obj/machinery/autodoc): ex act(3)
do explosion(the floor (62,22,3) (/turf/open/floor/mainship), -1, 3, 5, 6, 1, 0, 0)
world: ImmediateInvokeAsync("some_magic_bullshit", /proc/do_explosion (/proc/do_explosion), the floor (62,22,3) (/turf/open/floor/mainship), -1, 3, 5, 6, 1, 0, 0)
explosion(the floor (62,22,3) (/turf/open/floor/mainship), -1, 3, 5, 6, 1, 0, 0)
cannon round (/datum/ammo/rocket/ltb): drop nade(the floor (62,22,3) (/turf/open/floor/mainship))
cannon round (/datum/ammo/rocket/ltb): on hit turf(the floor (62,22,3) (/turf/open/floor/mainship), the cannon round (/obj/projectile))
the cannon round (/obj/projectile): projectile batch move(2)
the cannon round (/obj/projectile): process(2)
Projectiles (/datum/controller/subsystem/processing/projectiles): fire(0)
Projectiles (/datum/controller/subsystem/processing/projectiles): ignite(0)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): Loop()
Master (/datum/controller/master): StartProcessing(0)

**Comment by psykzz** [comment] 2020-07-04 18:34
Closed as can't reproduce

**Closed by psykzz** 2020-07-04 18:34 UTC
Labels: Can't Reproduce
