### ISSUE TITLE
Resin Walls delete light

### ISSUE THREAD

**Issue by Fireiy** [tgstation/TerraGov-Marine-Corps#2098] opened 2019-06-24 01:44 UTC

**Comment by Rohesie** [comment] 2019-06-24 14:28
#1964

**Comment by DominikPanic** [comment] 2019-06-25 12:39
Unable to reproduce, please provide better steps for reproduction.
https://puu.sh/DKz1A/295bb3b3ca.mp4

**Comment by DominikPanic** [comment] 2019-06-25 12:49
Also duplicate of #2072

**Closed by DominikPanic** 2019-06-25 12:49 UTC
Labels: Bug
