### ISSUE TITLE
Heavily Nerf/Remove Autodocs

### ISSUE THREAD

**Issue by CharlieDownsin** [tgstation/TerraGov-Marine-Corps#976] opened 2019-03-04 22:20 UTC
I tend to play as a Doctor/Scientist a lot and it's come to my attention through numerous rounds that an overwhelmingly majority of doctors (especially new ones) are using these machines as PRIMARY tools of treating any and all injuries. The current "standard" doctor round on the server looks something like this:

---------------------

1. Spawn as doctor and stand in the lobby idling. (Most of them don't even dare to try doing stuff with chems)

2. Wait until injured is teleported/walks into lobby. Grab them and toss them into the autodoc, then go back to standing in the lobby, waiting.

3. Have more injured arrive with Autodocs full and proceed to panic & OD people on drugs & toss them around medbay unintelligibly until all faith is lost in them & go SSD/enter sleeper and never play doctor again.

---------------------

To put it bluntly, these things are making bald doctors go balder into a downspiral of not bothering to learn about their role in the slightest as there is no incentive or need for them to do so. This sort of consequence has extensively been seen on other TG servers where "doctors" are doing nothing but tossing people into "fix everything" devices which you don't need to be a doctor to do in the first place, making the entire role itself completely moot.

Proposed possible (in no particular order) changes:

1. Double/Triple the existing time it takes for procedures to be done in the machines to make the victims to hate them.

2. Add reasonable chances for horrendous failures/malfunctions, possibly critical ones that add injuries and/or grossly worsen conditions.

3. Remove one Autodoc outright and make the remaining one unable to perform embryo removal.

4. Remove them both entirely and have there be a legitimate need for doctors on the ship.

**Comment by Alterist** [comment] 2019-03-05 04:03
> Remove one Autodoc outright and make the remaining one unable to perform embryo removal.
#980

**Comment by DominikPanic** [comment] 2019-03-05 20:07
You should post this either in #dev-general or on the Forums official suggestions thread. We do listen to feedback and as you can already see here Alterist already has this included in one of their PRs. The reason I'm closing this though is that GitHub is for bug reports only, and this is more of a balance concern as currently there being 2 autodocs is not a bug.

**Closed by DominikPanic** 2019-03-05 20:07 UTC
