### ISSUE TITLE
Brandon 'Heathen' Hummel / Maxim Drugimoi - tank door cell is frozen

### ISSUE THREAD

**Issue by Monikawales** [tgstation/TerraGov-Marine-Corps#408] opened 2019-01-28 02:40 UTC
## Testmerges:
Cant enter tank seat
Big Red Round time GMT 02:00 01.28.2019

## Reproduction:
Ask Brandon 'Heathen' Hummel how to reproduce.
I put a lot of cupola and other ammo on a tank entrance.
Also tank entrance cell was similar location as a machinegun deployment system.
Maybe if someone man a a machinegun deployment system sit while tank entrance on it bug happens.

Ask Admin Francinum  for details.

Admin Francinum has helped with spawning a new tank
Also make tank smartgun  to shoot over barricades
Tank smartgun is always miss while binoculars are used. Integrated array module does no increase to accuracy. Zero hits on sniper ranges.
Also while holding a binoculars In a gunner seat And tank is moving - gun sometimes "stuck" and stops working at all. 
Screenshots
![resources](https://user-images.githubusercontent.com/45321263/51811680-25377480-22bf-11e9-9fdf-6752e18d3cc8.png)
![massive award](https://user-images.githubusercontent.com/45321263/51811681-25d00b00-22bf-11e9-9af5-339f207273f5.png)

**Comment by Alterist** [comment] 2019-01-28 03:59
The cupola gun missing at extended ranges is intentional. There's a accuracy falloff at a certain range

**Comment by Ghommie** [comment] 2019-01-28 05:35
Duplicate of #407 and fairly similar issues you already reported previously. But yea, zoom interaction within the tank are very clunky, and the hardpoints modules would need some more barricade trepassing.

**Comment by DominikPanic** [comment] 2019-02-04 06:54
Duplicate of #407

**Closed by DominikPanic** 2019-02-04 06:54 UTC
