### ISSUE TITLE
Pulling speed is not working properly for xenos

### ISSUE THREAD

**Issue by MoXuT0** [tgstation/TerraGov-Marine-Corps#1575] opened 2019-05-11 23:34 UTC
## Testmerges:

Round ID:  466 
BYOND Version:  512.1464 
Server revision compiled on:  
Master commit: 3af7941fdb65ab2c9c2bff10b7f3f4a560ca6909 
The following pull requests are currently test merged: 
#1568: 'Fixes a race condition init runtime' by DominikPanic at commit 524ae62dee 
#1559: 'Fixes the RPG being unable to shoot different ammo types.' by DominikPanic at commit 5e11be6046 
#1561: 'Fixes an ancient init runtime' by DominikPanic at commit 1ea06746e4 
#1562: 'Fixes Rohesie's runtime' by DominikPanic at commit 0dc8c48482 
#1563: 'Fixes evil emote runtime' by DominikPanic at commit 51d4ef746c 
#1564: 'Possibly fixes another runtime' by DominikPanic at commit cb3dd612ac 
#1552: 'Fixes otherwordly sound spamming.' by Ghommie at commit c9c84c5f0f 
#1540: 'Ports SSinput from /tg/' by DominikPanic at commit b2ac34218b 

## Reproduction:

[That is what xeno peek performance looks like.](https://gyazo.com/3a2769f2f0b695be3b978657daf09ba9)

**Comment by DominikPanic** [comment] 2019-05-12 13:40
Unable to reproduce, unless I get steps to reproduce this issue I cannot fix it. This could have been caused by bad admin varedits that were present that round, unless this issue reappears it was most likely that.

https://puu.sh/DrjDF/f47da45236.mp4
https://puu.sh/DrjA8/ef1d56cd80.mp4

**Comment by MoXuT0** [comment] 2019-05-12 13:47
Probably caused by admemes, I’ll try to reproduce it on next test. Also try pulling xenos from different hives and vise versa, hive datum was fucked up that round.

**Comment by DominikPanic** [comment] 2019-05-12 13:52
https://puu.sh/DrjXJ/32048de6b8.mp4

Works properly, but during that round a very bad variable was edited that produced over 250kb of runtimes

**Comment by InterroLouis** [comment] 2019-05-12 22:16
This is still a problem, and a real problem. 
Server-Side Code Modifications: https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm

Round ID: 468
BYOND Version: 512.1464
Server revision compiled on: 
Master commit: 11d4be9bf65b5b133a09b087366a6e01a1cb8cd0
The following pull requests are currently test merged:
#1540: 'Ports SSinput from /tg/' by DominikPanic at commit 9cda3966b7
#1552: 'Fixes otherwordly sound spamming.' by Ghommie at commit c9c84c5f0f
#1564: 'Possibly fixes another runtime' by DominikPanic at commit cb3dd612ac
#1563: 'Fixes evil emote runtime' by DominikPanic at commit 51d4ef746c
#1562: 'Fixes Rohesie's runtime' by DominikPanic at commit 0dc8c48482
#1561: 'Fixes an ancient init runtime' by DominikPanic at commit 1ea06746e4
#1568: 'Fixes a race condition init runtime' by DominikPanic at commit 524ae62dee
#1556: 'adding tox bottles to med vendors' by Ghommie at commit 4c9591202f
#1557: 'Adds laughter, makes contraband pills not so bad.' by Ghommie at commit 24766e0314
#1571: 'Stops dropship sentries from processing while not deployed.' by Ghommie at commit 9542568d3d
#1580: 'Gives CLF leader ammo.' by DominikPanic at commit ed36f0c78b
#1578: 'Xenos now break barrels properly.' by DominikPanic at commit e5729fcae4
#1577: 'Runner balance tweaks' by Rohesie at commit cff6a9abc4

Local commit: bb8f7155784482511799ee8ee0a0d8f7ffa787d5
Server tools version: /tg/station 13 Server v3.2.6.2
TMs for the round.

**Comment by DominikPanic** [comment] 2019-05-12 22:59
Finally reproduced and fixed after someone told me it's with xenos dragging and stopping dragging dead human bodies.

**Comment by MoXuT0** [comment] 2019-05-12 23:55
Drones also seem to ignore some drag speed changes as for Round ID:  469.

**Comment by DominikPanic** [comment] 2019-05-13 08:55
> 
> 
> Drones also seem to ignore some drag speed changes as for Round ID: 469.

Server wasn't updated, but it is fixed.

**Closed** 2019-05-18 20:51 UTC
Labels: Bug
