### ISSUE TITLE
Can't click on tiles you can't see again.

### ISSUE THREAD

**Issue by Lumipharon** [tgstation/TerraGov-Marine-Corps#9635] opened 2022-02-13 02:46 UTC
### Description

You can't click/shoot etc onto tiles you can't see (i.e. dark etc).

### Test Merges

The following pull requests are currently test merged:
[#8932: 'Icarus Shipyard. (New map)' by vilereaver41 at commit 7157f2d2bf](https://github.com/tgstation/TerraGov-Marine-Corps//pull/8932)
[#9569: 'Xenomorphs cannot use most abilities nor attack while on a solid turf (e.g. a resin wall)' by DeltaFire15 at commit 069cbc60e3](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9569)
[#9629: 'Deployables can no longer be deployed into nullspace' by Notamaniac at commit 8e5c02f3de](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9629)

### Reproduction Steps

Try shoot into darkness
Nothing happens
Cry
Die

**Comment by Notamaniac** [comment] 2022-02-16 12:10
It's odd, I can't reproduce this locally, but I can reproduce it in EORD on the server.

**Comment by Losenis** [comment] 2022-02-16 15:55
Only fix I've had work is closing the client and booting it up again

**Comment by BraveMole** [comment] 2022-08-03 15:15
Most probably byond issue, won't fix

**Comment by ivanmixo** [comment] 2023-09-04 03:59
Reconnecting fixes this and yeah seems like a byond issue. Bleh.

**Closed by ivanmixo** 2023-09-04 03:59 UTC
Labels: Bug, Byond Issue
