### ISSUE TITLE
missing PACMAN sprite

### ISSUE THREAD

**Issue by factoryman942** [tgstation/TerraGov-Marine-Corps#3215] opened 2019-10-31 21:08 UTC
![image](https://user-images.githubusercontent.com/20996272/67986192-5ebc5800-fc22-11e9-87cf-4b0f15438919.png)
![image](https://user-images.githubusercontent.com/20996272/67986275-8dd2c980-fc22-11e9-99f0-54761c970fbd.png)

TMs:
#3210: 'Fixes my armor sprites positioning' by Kuro-ai at commit 2782246a0b
#3207: 'Make tackle damage respect 80% of armor value' by Kuro-ai at commit aea4ddb413
#3205: 'Some fixes for Icy Caves Map' by Isy232 at commit d774d8e9c1
#3175: 'Signals cleanup' by Rohesie at commit 6ab75d4294
#3159: 'fix shuttle calldown memes' by spookydonut at commit 2f08dd043a
#3173: 'Some damage de-escalation stuff.' by Isy232 at commit cc0d892492
#3120: 'tgui-next' by spookydonut at commit 072cecc246
#3213: 'Makes Helmets Smaller' by XSlayer300 at commit 55cbf4bf09
#3192: 'Redesigned Player Setup' by XSlayer300 at commit c152032beb

Icy caves, west cave APC room
Round ID 1571

**Comment by Hughgent** [comment] 2019-11-07 02:31
![image](https://user-images.githubusercontent.com/45076386/68355251-50fc4c00-00d4-11ea-8626-0ab812812ca0.png)

Unable to reproduce on current master.

**Comment by Rohesie** [comment] 2019-11-07 09:24
This was an issue with TGUI-Next but it's fixed now.

**Closed by Rohesie** 2019-11-07 09:24 UTC
