### ISSUE TITLE
Armat Systems Attachments Vendor electrick shock

### ISSUE THREAD

**Issue by Monikawales** [tgstation/TerraGov-Marine-Corps#1314] opened 2019-04-20 21:05 UTC
## Reproduction:
1. Press hacked electrified Armat Systems Attachments Vendor by hand
2. Electric shock
3. Someone press Armat Systems Attachments Vendor
4. Char lies on req table electrocuted every time anyone press Armat Systems Attachments Vendor

**Comment by Monikawales** [comment] 2019-04-20 21:25
Also m42a dont have ammo hood

**Comment by DominikPanic** [comment] 2019-04-20 21:28
1. Include testmerges. Always. Please.
2. One bug per report unless they are related.

**Comment by DominikPanic** [comment] 2019-05-03 12:35
The first issue has unable to been reproduced, most likely a TM issue fixed in one of my attackby PRs. The second one is not a bug but a missing feature.

**Closed by DominikPanic** 2019-05-03 12:35 UTC
