### ISSUE TITLE
Player Controlled AI Test Result

### ISSUE THREAD

**Issue by Urthrem** [tgstation/TerraGov-Marine-Corps#1908] opened 2019-06-13 03:09 UTC
After the AI test here are few issues I have found during the round.

1st. Sound Played with Each AI Announcement was either unchanged or set to play wrong sound file as it played "Command Update" instead of one for AI.

2nd. While Medical Overlay functioned properly the Sec and Squad didn't function at all, it was possible to toggle both on and off but without any overlay visible.

3rd. Severe lack of Crew Manifest joined up with lack of Inspecting (even with Shift Clicking) of the marines made it impossible with identifying the ranks in certain situations.

4th. Lack of ability to use buttons, consoles (Not including Dropship controls) to provide Command and Logistics Related support during the events when Command Staff was unavailable.

There was also an issue with camera placement but that won't fit in due to a fact that cameras weren't placed with AI in thought in the first place.

**Comment by DominikPanic** [comment] 2019-06-13 07:50
```
1st. Sound Played with Each AI Announcement was either unchanged or set to play wrong sound file as it played "Command Update" instead of one for AI.
```
Intended.
```
2nd. While Medical Overlay functioned properly the Sec and Squad didn't function at all, it was possible to toggle both on and off but without any overlay visible.
``` 
A bug, will fix.
```
3rd. Severe lack of Crew Manifest joined up with lack of Inspecting (even with Shift Clicking) of the marines made it impossible with identifying the ranks in certain situations.
```
Please put feature requests in #dev-general.
```
4th. Lack of ability to use buttons, consoles (Not including Dropship controls) to provide Command and Logistics Related support during the events when Command Staff was unavailable.
```
Same as above.

**Comment by DominikPanic** [comment] 2019-06-13 08:00
2. could be related to #1901 since I could not reproduce it locally @Rohesie test this please

**Comment by Rohesie** [comment] 2019-06-14 08:47
![dreamseeker_JK0kfsBXKy](https://user-images.githubusercontent.com/42041276/59496488-e702b200-8e67-11e9-9382-877949643934.png)

Doesn't seem to be the case here.

**Comment by DominikPanic** [comment] 2019-06-15 11:39
Let's see if it happens again.

**Comment by DominikPanic** [comment] 2019-06-25 14:01
Seems to be alright now that #1901 was merged

**Closed by DominikPanic** 2019-06-25 14:01 UTC
Labels: Bug
