### ISSUE TITLE
Xenos can conga at lightspeed

### ISSUE THREAD

**Issue by RipGrayson** [tgstation/TerraGov-Marine-Corps#1576] opened 2019-05-11 23:38 UTC
## Testmerges:

#1568: 'Fixes a race condition init runtime' by DominikPanic at commit 524ae62dee
#1559: 'Fixes the RPG being unable to shoot different ammo types.' by DominikPanic at commit 5e11be6046
#1561: 'Fixes an ancient init runtime' by DominikPanic at commit 1ea06746e4
#1562: 'Fixes Rohesie's runtime' by DominikPanic at commit 0dc8c48482
#1563: 'Fixes evil emote runtime' by DominikPanic at commit 51d4ef746c
#1564: 'Possibly fixes another runtime' by DominikPanic at commit cb3dd612ac
#1552: 'Fixes otherwordly sound spamming.' by Ghommie at commit c9c84c5f0f
#1540: 'Ports SSinput from /tg/' by DominikPanic at commit b2ac34218b

## Reproduction:

Become a xeno runner, grab another xeno. Have that xeno grab another xeno, add as many xenos as you want to the growing line. 

Move while still holding onto your sister. 
All of the xenos will be pulled at the speed of their leader potentially allowing them to cross an entire ship in the span of less than 15 seconds as a complete group.

**Comment by DominikPanic** [comment] 2019-05-11 23:39
Duplicate of #1575

**Closed by DominikPanic** 2019-05-11 23:39 UTC
