### ISSUE TITLE
Setup Character Error

### ISSUE THREAD

**Issue by Anystar1** [tgstation/TerraGov-Marine-Corps#4841] opened 2020-09-19 14:41 UTC
## Reproduction:
when i click setup character an error occurs before this i was making a character when it said something in chat about the save not working or overwriting or something along those lines when an error pops up

**Comment by TiviPlus** [comment] 2020-09-19 15:40
Duplicate of https://github.com/tgstation/TerraGov-Marine-Corps/issues/4799 ?

**Closed** 2020-09-21 12:21 UTC
Labels: Bug, Duplicate, Test Merge Bug
