### ISSUE TITLE
quick equip undefinited proc runtime.

### ISSUE THREAD

**Issue by Ghommie** [tgstation/TerraGov-Marine-Corps#1689] opened 2019-05-30 15:20 UTC
## Testmerges:
None, local test.

## Reproduction:
Be anything but a human mob. Press E. Look at the runtime viewer.

```
  usr: Ghom/(monkey (778))
  usr.loc: (Hallway Starboard (174, 76, 3))
[2019-05-30 14:47:02.160] runtime error: undefined proc or verb /mob/living/carbon/monkey/quick equip().
```

It doesn't ruin the gaming experience, but it does spammily clog the runtimes logs.

**Comment by DominikPanic** [comment] 2019-05-30 15:20
Duplicate of #1647

**Closed by DominikPanic** 2019-05-30 15:20 UTC
