### ISSUE TITLE
Imaginary Friend Bypasses Respawn

### ISSUE THREAD

**Issue by neohenry** [tgstation/TerraGov-Marine-Corps#5563] opened 2020-12-25 01:32 UTC
## Reproduction:

https://www.youtube.com/watch?v=B4jaCdQD-XA&feature=youtu.be

1) Be mentor
2) Dies as beno or marine
3) Respawn time takes a while
4) Become imaginary friend
5) Get out of being imaginary friend
6) Respawn time go bye bye

**Comment by Hughgent** [comment] 2020-12-25 02:27
Man this is a real 'humdinger' of a bug.

Should it be 'fixed' or should it just be available to mentors who, having left their bodies to do mentor stuff and return to find their original body dead (mostly xeno I suspect), be allowed to respawn using this method?

**Comment by Hughgent** [comment] 2020-12-25 02:35
The reason its allowing respawn is because the imaginary friend camera is a mob, and it calls `ghostize()` on that mob, which sets its `time_of_death` to the `mob`'s time of death, and since the imaginary friend camera `mob` "has never died before" time of death is `0` which bypasses respawn timers.

**Comment by TiviPlus** [comment] 2020-12-27 14:15
Duplicate of #5442

**Closed by TiviPlus** 2020-12-27 14:15 UTC
