### ISSUE TITLE
Can't eject from hypersleep chamber.

### ISSUE THREAD

**Issue by MiniMeatwad** [tgstation/TerraGov-Marine-Corps#987] opened 2019-03-05 23:37 UTC
## Reproduction: Get put in a hypersleep chamber, either by force or willingly, you cannot be removed or exit the hypersleep chamber, practically like putting someone out of the round by click dragging them.
![dreamseeker_2019-03-05_18-30-45](https://user-images.githubusercontent.com/22848292/53844844-050d6c00-3f75-11e9-9d7a-450d30459702.png)

**Comment by DominikPanic** [comment] 2019-03-14 13:44
This is intended for hypersleepers of that type, but Ghommie is refactoring it anyway so I'm closing this as it's not a bug.

**Closed by DominikPanic** 2019-03-14 13:44 UTC
Labels: Bug
