### ISSUE TITLE
Xeno sight was bugged in certain places and you could not see threw certain spaces with clear LOS. And turning off NVGs blinded you.

### ISSUE THREAD

**Issue by Pariah919** [tgstation/TerraGov-Marine-Corps#1634] opened 2019-05-25 01:52 UTC
The following pull requests are that were test merged:
#1627: 'fixes weeds' by spookydonut at commit 1e4416a9be
#1628: 'Warrior lunges grab humans in their offhand' by psykzz at commit e4b5114079
#1623: 'Balance tweaks.' by Rohesie at commit bc93d71d05
#1596: 'Inspection on the little smoke runtime.' by Ghommie at commit 31870a2326
#1600: 'Add ghost hud & alerts from TG' by psykzz at commit 79c5853e1a

**Comment by DominikPanic** [comment] 2019-05-25 10:14
Duplicate of #1635

**Closed by DominikPanic** 2019-05-25 10:14 UTC
