### ISSUE TITLE
Boiler glowing without enough globs stored

### ISSUE THREAD

**Issue by Lefunny** [tgstation/TerraGov-Marine-Corps#8411] opened 2021-09-24 19:17 UTC
### Description

Boiler keep glowing even when the globs storeds arent enough for the glow

### Test Merges

#8303: 'Jaeger refactor.' by hyper2snyper at commit e0c7a0b5cf
#8301: 'Combat Robots Race' by TiviPlus at commit 273e8c965a
#8384: 'Fix weed decaying' by BraveMole at commit 0e09679c3f
#8400: 'Hotfix weed' by BraveMole at commit c9344c5dad

### Reproduction Steps

1. Evolve into boiler
2. get max glob storage
3. use your globs and wait for it to get below two globs stored
4. Now you glow forever like a lamp

**Comment by BraveMole** [comment] 2021-09-24 19:43
duplicate of another issue

**Closed by BraveMole** 2021-09-24 19:43 UTC
Labels: Bug
