### ISSUE TITLE
Attachments don't save in loadout vendor for weapons stored in jaegar general storage

### ISSUE THREAD

**Issue by Jalopkomit18** [tgstation/TerraGov-Marine-Corps#10951] opened 2022-09-13 23:58 UTC
### Description

Weapons that are stored in the jaegar general storage module do not save attachments in the loadout vendor. 

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [16490](https://scrubby.melonmesa.com/round/16490)
BYOND Version: 514.1585
Server revision compiled on:
Master commit: [e0eedcf94f4aec6334771bd8ba4548bcd6b44b7e](https://github.com/tgstation/TerraGov-Marine-Corps//commit/e0eedcf94f4aec6334771bd8ba4548bcd6b44b7e)
The following pull requests are currently test merged:
[#10793: 'New Map: Gelida IV [MDB ignore]' by RipGrayson at commit a99f7bfc47](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10793)

Local commit: 986c12054baeb20072d0f01e0a808b4fa76bfa5c
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

1. Put weapon with attachments in jaegar general storage module
2. Save loadout
3. Vend loadout, no attachments on the weapons inside the storage module

**Comment by Xander3359** [comment] 2023-02-28 21:49
Duplicate of https://github.com/tgstation/TerraGov-Marine-Corps/issues/9349

**Closed** 2023-02-28 21:53 UTC
Labels: Bug
