### ISSUE TITLE
Slashing APC's as xeno is bugged

### ISSUE THREAD

**Issue by MoXuT0** [tgstation/TerraGov-Marine-Corps#1833] opened 2019-06-08 23:36 UTC
## Testmerges:

Round ID:  559 
BYOND Version:  512.1464 
Server revision compiled on:  
Master commit: 12392177e5c17c10c55c963bcbc06879e8df6911 
The following pull requests are currently test merged: 
#1816: 'Fixes blood overlay for boots, adds different icon for pyro boots' by MoXuT0 at commit 3b44ed3f99 
#1817: 'Gives B18 tacticool gloves' by MoXuT0 at commit 8715b3a537 
#1812: 'Fixes airlock welding' by DominikPanic at commit 050cd10e76 
#1814: 'Makes AI report verbs more modular.' by DominikPanic at commit 0ac09beb93 
#1805: 'Adds a slight delay to watchlists to prevent join race condition' by DominikPanic at commit 4d45a3604e 
#1808: 'Combines the rank/equipment/squad admin verbs, slight PP tweaks' by DominikPanic at commit 8995384498 
#1789: 'Fixes layers of items related to actions' by DominikPanic at commit 1bb8cfae5a 
#1757: 'Adds new firing sounds for some weapons' by MoXuT0 at commit ac896e083a 
#1758: 'Adds more explosion sounds' by MoXuT0 at commit 67c096955e 
#1766: 'LOS Reduces screech effectiveness' by psykzz at commit 3f86655d11 
#1801: 'Adds round IDs to the note panel.' by DominikPanic at commit fcc3d440bc 
#1804: 'Cleans up some dirty perspective modifications' by DominikPanic at commit 78e7ed6c21 
#1803: 'Makes the AI unable to interact with dropship doors.' by DominikPanic at commit 511e0a1b48 
#1810: 'Fixes an admin runtime.' by DominikPanic at commit 553c1083ad 
#1815: 'Makes the pod launcher logging better.' by DominikPanic at commit ce68163d5c 
#1820: 'Fixes a sleeper runtime' by DominikPanic at commit 7c2d968741 
#1818: 'Fixes a to_chat runtime.' by DominikPanic at commit 8cd7553b01 
#1538: 'Mends a not-so-little race condition smoke runtime on rockets & co.' by Ghommie at commit d8e3156a0d 
#1825: 'Standarizing pills init.' by Ghommie at commit a13facf4ae 

## Reproduction:

Can't stop fumbling.

![eeeee](https://user-images.githubusercontent.com/34478337/59153331-45dabc80-8a5f-11e9-92d7-84154257ba56.png)

**Comment by DominikPanic** [comment] 2019-06-08 23:40
Unable to reproduce, worked fine for me. Could you provide more information?

**Comment by MoXuT0** [comment] 2019-06-08 23:42
Dunno, that APC was built by engie. He may unlocked it or something.

**Comment by MoXuT0** [comment] 2019-06-08 23:45
This even works for broken apc's.

![изображение](https://user-images.githubusercontent.com/34478337/59153378-a28aa700-8a60-11e9-9f5f-37148a9312f3.png)

**Comment by DominikPanic** [comment] 2019-06-08 23:48
https://puu.sh/DDsqt/a4ecd1a540.mp4

**Comment by DominikPanic** [comment] 2019-06-08 23:55
Again if this is a common problem I recommend sending a video or a detailed description

**Comment by DominikPanic** [comment] 2019-06-08 23:59
Nevermind, figured it out

**Comment by DominikPanic** [comment] 2019-06-10 17:32
Fixed in #1834

**Closed by DominikPanic** 2019-06-10 17:32 UTC
Labels: Bug
