### ISSUE TITLE
Camera Bug

### ISSUE THREAD

**Issue by GhostAvenger** [tgstation/TerraGov-Marine-Corps#2489] opened 2019-07-29 07:43 UTC
## Reproduction:
Use the overwatch squad camera after the ship crashes on Crashed Gamemode.

This bug lets you see the entire map, even without camera access. Me being a synth also let me see in the dark, basically giving me ghost vision of the entire map

Round ID 760

**Comment by DominikPanic** [comment] 2019-07-29 10:47
I can't reproduce this, are you sure it's that simple?

**Comment by DominikPanic** [comment] 2019-07-29 17:06
Regardless #2492 should help with it, so please comment if you see it again.

**Comment by GhostAvenger** [comment] 2019-07-29 20:30
If I remember everything I did, I was a synth, used the console, selected a squad member, and it gave me vision on everything. I will see if I am reproduce it

**Comment by GhostAvenger** [comment] 2019-08-01 00:58
I could not reproduce it today. @Rohesie was there when I reported this to Ahelp and tested it too.

**Comment by DominikPanic** [comment] 2019-08-12 20:58
I'll leave this open for some time, so far it seems like it didn't happen again

**Comment by DominikPanic** [comment] 2019-08-17 01:28
Seems like my PR fixed it, thus I'm closing this

**Closed by DominikPanic** 2019-08-17 01:28 UTC
