### ISSUE TITLE
Xenos can make themselves un-hittable by building a wall inside of themselves.

### ISSUE THREAD

**Issue by AnCopper** [tgstation/TerraGov-Marine-Corps#6921] opened 2021-05-21 18:49 UTC
## Reproduction:

This is a pretty dumb cheese start, it allows them to melt cades and use abilites while being un-hittable.

**Comment by TiviPlus** [comment] 2021-05-22 08:41
dupe of 6837

**Closed by TiviPlus** 2021-05-22 08:41 UTC
