### ISSUE TITLE
Hivemind camera does not return to Hivemind mob if you stand still on a weedless tile.

### ISSUE THREAD

**Issue by XSlayer300** [tgstation/TerraGov-Marine-Corps#4808] opened 2020-09-13 05:34 UTC
## Testmerges:
#4783 #4763 #4727 #4487 #4786 #4743 #4762 #4777 #4793 #4795 #4800 #4805 #4806

## Reproduction:

1. Create weeds as hivemind.
2. Move to a tile that is weedless with nearby weeds.
3. Let a marine knife all of the weeds, hivemind must not move at all.
4. Hivemind can still weed even if the tile is weedless.

**Comment by Chaznoodles** [comment] 2020-09-13 11:30
Duplicate of #4761

**Comment by TiviPlus** [comment] 2020-09-17 19:31
what chaz said

**Closed by TiviPlus** 2020-09-17 19:31 UTC
