### ISSUE TITLE
Windoors can be shot throught

### ISSUE THREAD

**Issue by Delams-The-SM** [tgstation/TerraGov-Marine-Corps#7707] opened 2021-07-31 12:37 UTC
### Description

Windoors can be shot throught if the shooter is on the tile windoor is

### Test Merges

Round ID: [10103](https://scrubby.melonmesa.com/round/10103)
BYOND Version: 514.1557
Server revision compiled on: 
Master commit: 1bf9d399a5c9c111ec98eee911ecbd7be760b1f5
The following pull requests are currently test merged:
#7650: 'Icy cave's Expansion' by vilereaver41 at commit f9fc019393
#7475: 'Makes red dot sight reduce aim mode fire delay by 50%' by Walarks at commit 27d553d42d
#7404: 'Sentry Rework' by hyper2snyper at commit 4ab41dfc37
#7210: 'Autodocs can now start on their own' by QualityVan at commit 6fca7f7957
#7618: 'King of the hill Civil War' by BraveMole at commit 4d3bd889d8

Local commit: cbf6f6f07e0254e6ae34d56140f6fd45bb13e9b2
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

1) stand on tile windoor is
2) shoot in direction it is
3) perfect cade that blocks smoke based attacks

### Screenshots

https://user-images.githubusercontent.com/66973657/127738752-ea251355-8588-4de0-8aca-50c2d2cfb2e9.mp4

**Comment by Delams-The-SM** [comment] 2021-08-08 02:25
Same appears to happen with normal directional windows

**Comment by Delams-The-SM** [comment] 2021-08-08 07:21
Same applies to directinal windows but hmm ... considering just how fragile they are especially to crushers, lets just call em glass cades oki ?

**Comment by BraveMole** [comment] 2021-09-07 11:52
Duplicate of another issue

**Closed by BraveMole** 2021-09-07 11:52 UTC
Labels: Bug
