### ISSUE TITLE
Defib bug?

### ISSUE THREAD

**Issue by arkon897** [tgstation/TerraGov-Marine-Corps#5984] opened 2021-02-09 13:28 UTC
Round ID 7219, i was Ancient Drone (Duran), Byond name is Arkon897, at about 1330 approximately someone started to defib a marine, by the name of Mihail Aleksandravich, i was being offered the body as if it was mine thats about it

**Comment by TGCMbetcher** [comment] 2021-02-09 18:08
Yea thats been around for a while. I thought it was because I followed one and they got defibbed but then it happened again later when Y hadnt followed anyone.

**Comment by XSlayer300** [comment] 2021-02-13 23:29
Duplicate of #5627 .

**Comment by TiviPlus** [comment] 2021-02-14 14:55
Duplicate of #5627

**Closed by TiviPlus** 2021-02-14 14:55 UTC
